/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crackeadordemd5;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author JUDITH
 */
public class ventanaInicial extends javax.swing.JFrame {

    String[] texto;
    String[] usuario;
    String[] clave;
    MD5 md5;
     proceso []hil;
     cerrar cierre;

    public ventanaInicial() {
        this.texto = new String[101];
        this.usuario = new String[101];
        this.clave = new String[101];
        this.hil = new proceso[7];

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarArchivo = new javax.swing.JFileChooser();
        BuscarArchivo = new javax.swing.JButton();
        hilos = new javax.swing.JLabel();
        botonmas = new javax.swing.JButton();
        botonmenos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        empezarBusqueda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BuscarArchivo.setText("Buscar archivo");
        BuscarArchivo.setToolTipText("");
        BuscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarArchivoActionPerformed(evt);
            }
        });

        hilos.setText("1");

        botonmas.setText("+");
        botonmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmasActionPerformed(evt);
            }
        });

        botonmenos.setText("-");
        botonmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmenosActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de hilos");

        empezarBusqueda.setText("Empezar busqueda");
        empezarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(BuscarArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(botonmenos)
                .addGap(32, 32, 32)
                .addComponent(hilos)
                .addGap(34, 34, 34)
                .addComponent(botonmas)
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(empezarBusqueda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarArchivo)
                    .addComponent(hilos)
                    .addComponent(botonmas)
                    .addComponent(botonmenos))
                .addGap(34, 34, 34)
                .addComponent(empezarBusqueda)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarArchivoActionPerformed
        String aux = "";

        int cont = 0;
        try {
            JFileChooser file = new JFileChooser();
            file.showOpenDialog(file);

            File abre = file.getSelectedFile();

            if (abre != null) {
                FileReader archivos = new FileReader(abre);
                BufferedReader lee = new BufferedReader(archivos);
                while ((aux = lee.readLine()) != null) {

                    texto[cont] = aux;
                    String[] split = aux.split("::");
                    usuario[cont] = split[0];
                    clave[cont] = split[1];

                    cont++;
                }
                lee.close();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex + "" + "\nNo se ha encontrado el archivo",
                    "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BuscarArchivoActionPerformed

    private void botonmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmasActionPerformed
        int Nhilos = Integer.parseInt(hilos.getText());
        if (Nhilos < 6) {
            Nhilos++;
        }
        hilos.setText("" + Nhilos);
    }//GEN-LAST:event_botonmasActionPerformed

    private void botonmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmenosActionPerformed
        int Nhilos = Integer.parseInt(hilos.getText());
        if (Nhilos > 1) {
            Nhilos--;
        }
        hilos.setText("" + Nhilos);
    }//GEN-LAST:event_botonmenosActionPerformed

    private void empezarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarBusquedaActionPerformed
    
       
            int ite = Integer.parseInt(hilos.getText());
            int con=0;
            cierre =new cerrar(ite,con);
            for (int p = 0; p < ite; p++) {
            hil[p]= new proceso(p,ite,clave,usuario,cierre);
		hil[p].start();
            }
        
        

    }//GEN-LAST:event_empezarBusquedaActionPerformed

   

    public static void main(String args[]) {
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarArchivo;
    private javax.swing.JButton botonmas;
    private javax.swing.JButton botonmenos;
    private javax.swing.JFileChooser buscarArchivo;
    private javax.swing.JButton empezarBusqueda;
    private javax.swing.JLabel hilos;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables


}
